stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - rm -rf /home/lars/route/*
    - cp -av * /home/lars/route
  environment:
    name: production
    url: https://routeconnect.tk
  when: manual
  only:
  - master
